### ISSUE TITLE
Checkbox for "This will delete all cookies for the domain you're recording for."

### ISSUE THREAD

**Issue by Zarkonnen** [SeleniumBuilder/selenium-builder#18]
In some circumstances, this is not what you want. This should be a checkbox, though turned on by default.

**Comment by hhaamm** [comment]
This will be useful for me too. Is there a starting point in the code I can look at?

**Comment by Zarkonnen** [comment]
[This](https://github.com/SeleniumBuilder/selenium-builder/blob/master/seleniumbuilder/content/html/builder/record.js#L141) is the line that does the deed. If you add a checkbox to [here](https://github.com/SeleniumBuilder/selenium-builder/blob/master/seleniumbuilder/content/html/gui.html#L68)/[here](https://github.com/SeleniumBuilder/selenium-builder/blob/master/seleniumbuilder/content/html/builder/views/startup.js) to make it toggle-able that should do it.

**Comment by Zarkonnen** [comment]
Implemented, will be in the next release.

**Comment by hhaamm** [comment]
@Zarkonnen Awesome!
