### ISSUE TITLE
RunLocally

### ISSUE THREAD

**Issue by jefleponot** [SeleniumBuilder/selenium-builder#29]
Hello,

why can't we run locally now test ?

Regards,
Jef

**Comment by Zarkonnen** [comment]
See [here](https://github.com/SeleniumBuilder/selenium-builder/blob/master/README.md). Basically, the webdriver playback code made massive use of eval(), and eval() is now strictly forbidden by Mozilla.

I'm looking into using Marionette to recreate local playback.
